# This file was generated by GoReleaser. DO NOT EDIT.
class Gofindup < Formula
  desc "Simple find up utility"
  homepage "https://github.com/ojizer/gofindup"
  version "1.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/ojizero/gofindup/releases/download/v1.1.0/gofindup_1.1.0_darwin_amd64.tar.gz"
    sha256 "91b7e76e0f44246bc0f70271dc5e95be1c95ea0842a9f27bfdaceb99c61f58cb"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/ojizero/gofindup/releases/download/v1.1.0/gofindup_1.1.0_linux_amd64.tar.gz"
      sha256 "11ec4a7d285c0d7006bb017f501468800b446cfff397eb381ce15d0c71471c8a"
    end
  end

  def install
    bin.install "gofindup"
  end
end
