# This file was generated by GoReleaser. DO NOT EDIT.
class Gofindup < Formula
  desc "Simple find up utility"
  homepage "https://github.com/ojizer/gofindup"
  version "1.1.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/ojizero/gofindup/releases/download/v1.1.2/gofindup_1.1.2_darwin_amd64.tar.gz"
    sha256 "ef3758b76fabb8a1596648bfa8d589989898a63dc5ecab07a9ec1fd36696472e"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/ojizero/gofindup/releases/download/v1.1.2/gofindup_1.1.2_linux_amd64.tar.gz"
      sha256 "58e571a8872b7d78d2838b13ce22a55edd07a427161bd7ad3ee3941fa8cc1899"
    end
  end

  def install
    bin.install "gofindup"
  end
end
