# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gomakehelp < Formula
  desc ""
  homepage ""
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ojizero/gomakehelp/releases/download/v1.0.0/gomakehelp_1.0.0_Darwin_arm64.tar.gz"
      sha256 "730b2a33f261380f730b1975810ebae6449eed0cfc7d89349ac9c740b44ae3b2"

      def install
        bin.install "gomakehelp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ojizero/gomakehelp/releases/download/v1.0.0/gomakehelp_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "02d17a7f1787c796e44196e4d86647c0ebc8edffcb1297ff76de67148125ae7e"

      def install
        bin.install "gomakehelp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ojizero/gomakehelp/releases/download/v1.0.0/gomakehelp_1.0.0_Linux_arm64.tar.gz"
      sha256 "7618ac0140682187bffbc01c1251ed8846f9089361292ac333f4c58aa507a927"

      def install
        bin.install "gomakehelp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ojizero/gomakehelp/releases/download/v1.0.0/gomakehelp_1.0.0_Linux_x86_64.tar.gz"
      sha256 "219e0f55ee6ea08710a883baca5de29c655282a0ca4c0dbbfd759ab2fb87e0ec"

      def install
        bin.install "gomakehelp"
      end
    end
  end
end
